use_frameworks!

target 'LocalNotificationWrapper_Example' do
  pod 'LocalNotificationWrapper', :path => '../'

  target 'LocalNotificationWrapper_Tests' do
    inherit! :search_paths

    
  end
end
