language : objective-c 

osx_image: xcode9.1

#whitelist

xcode_workspace: Example/LocalNotificationWrapper.xcworkspace # path to your xcodeproj folder
xcode_scheme: LocalNotificationWrapper_Tests

script: xcodebuild test -workspace Example/LocalNotificationWrapper.xcworkspace -scheme LocalNotificationWrapper_Tests -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.3.1'
